- name: OpenShift Prereqs
  hosts: all
  become: yes
  vars_files:
  - "../{{workdir}}/AZs_By_Region.yml"  # I don't think i need this
  - "../{{workdir}}/AMIs_By_Region.yml"
  - "../{{workdir}}/aws_vars.yml"
  - "../{{workdir}}/deployment_vars.yml"
  vars:
    prereq_pkgs:
      - vim
      - tmux
      - ntp
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - yum-versionlock
    docker_version: 1.10.3
    docker_device: /dev/xvdb
  tasks:

    - name: verify cloud init bootstrap is complete
      command: grep finished /var/log/cloud-init.log
      changed_when: False

    - name: install prereq packages
      yum: name="{{ item }}" state=present
      with_items: prereq_pkgs

    - name: enable ntpd
      service: name=ntpd state=started enabled=yes

    - name: install docker
      yum: name="docker-{{ docker_version }}" state=present

    - name: lock docker version
      command: yum versionlock add "docker*"

    - name: generate docker-storage-setup config
      template: src=files/sysconfig.docker-storage-setup.j2 dest=/etc/sysconfig/docker-storage-setup

    - name: start and enable docker
      service: name=docker state=started enabled=yes

    - name: update all packages
      yum: name='*' state=latest update_cache=yes

- hosts: masters
  become: yes
  vars_files:
    - "../{{workdir}}/AZs_By_Region.yml"  # I don't think i need this
    - "../{{workdir}}/AMIs_By_Region.yml"
    - "../{{workdir}}/aws_vars.yml"
    - "../{{workdir}}/deployment_vars.yml"
  tasks:
    - name: create /etc/origin/master directory
      shell: " [ -d /etc/origin/master ] || mkdir -p /etc/origin/master"
      tags:
        - copy_ca_cert

    - name: Copy CA Cert to /root directory
      become: yes
      copy: "src=../{{workdir}}/{{ipa_ca}} dest=/etc/origin/master/ mode=0600"
      when: ipa_ca is defined
      tags:
       - copy_ca_cert
